### ISSUE TITLE
Style issue in sidebar mobile

### ISSUE THREAD

**Issue by preshpi** [preshpi/noteey#11]
Fix the texts to be responsive
<img width="238" alt="Screenshot 2024-01-13 at 10 55 57" src="https://github.com/preshpi/noteey/assets/80992383/2c3857f7-ba09-407f-9dcf-e6e2daa225bd">

**Comment by Samuel-Web-Dev** [comment]
You mean the text should not wrap and i should adjust the fontSize right??

**Comment by preshpi** [comment]
Yes
