### ISSUE TITLE
Improvement Suggestion - Implementing a Better Note Card Interaction

### ISSUE THREAD

**Issue by danielasakpa** [preshpi/noteey#19]
### Description

Currently, we're using `react-draggable` for the note card component, allowing users to freely move the card anywhere on the screen. While this provides a degree of flexibility, it can result in a messy layout, especially when users reload the page, and cards return to their original positions.

I'd like to propose an enhancement to the note card interaction using a more sophisticated framework, [DnD Kit](https://dndkit.com/). DnD Kit not only allows for drag-and-drop functionality but also enables the implementation of note cards in a fixed container. This way, users can still interact with the cards by swapping them within the container, providing a more structured and user-friendly experience.

### Example

Check out this [example](https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/presets-sortable-grid--swappable) to see how DnD Kit handles swappable note cards within a fixed container.

### Benefits

- **Consistent Layout**: Having a fixed container ensures a more organized and consistent layout, preventing the cards from being scattered randomly.
- **Persistent Positioning**: With DnD Kit, the positions of note cards can persist even after page reloads, offering a more stable user experience.

This enhancement would contribute to a more polished and user-friendly interface. Looking forward to your thoughts on this!

**Comment by preshpi** [comment]
Thanks, I didn't know about DND kit. I'll improve the interaction by using it.
