### ISSUE TITLE
I will like to contribute to the project 

### ISSUE THREAD

**Issue by Samuel-Web-Dev** [preshpi/noteey#5]
This is clever web Dev from Tiktok....I will love to contribute to this project and I will like to know where in particular you need my contribution in this project

**Comment by preshpi** [comment]
@Samuel-Web-Dev thanks for your interest. please go through the issues I created and pick on so I can assign it to you

**Comment by preshpi** [comment]
@Samuel-Web-Dev check the readme on how to get started

**Comment by preshpi** [comment]
@Samuel-Web-Dev are you familiar with the tech I’m using (just asking) 
I used tailwind, redux, typescript, and Firebase

**Comment by Samuel-Web-Dev** [comment]
Immediately i saw the tech you're using, I'm scared at the first place but i told myself let me go and learn more, i'm only confident in react, firebase for now....I'm sorry i don't think i will be able to contribute to the project since am not familiar with some of the tech skills you just listed, but i started learning Nextjs and TypeScript immediately, if the project is not that urgent, i will get back to you immediately i'm done learning them cuz i will learn them rapidly. Thanks for your understanding precious.

**Comment by preshpi** [comment]
@Samuel-Web-Dev you don’t have to be scared. You can take a look at the project and start contribute to the ones you can do, we learn by doing. If you need help you can let me know

**Comment by Samuel-Web-Dev** [comment]
Okay thanks, you're such an amazing person precious, which i aspired to be in this tech journey, i will really like to connect with you.

**Comment by preshpi** [comment]
Thanks 😊

**Comment by Samuel-Web-Dev** [comment]
> Thanks 😊

You're welcome
