### ISSUE TITLE
Delete and Deactivate account

### ISSUE THREAD

**Issue by preshpi** [preshpi/noteey#9]
As a user, I should be able to delete and deactivate my account.
<img width="976" alt="Screenshot 2024-01-13 at 10 52 10" src="https://github.com/preshpi/noteey/assets/80992383/ee5434bb-b422-4f05-9fcb-383232630d45">

**Comment by Samuel-Web-Dev** [comment]
Okay

**Comment by preshpi** [comment]
Fixed!
